server:
  port: 9999
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: jdbc
  application:
    name: config-server-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fsl_springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456789
  cloud:
    config:
      label: master
      server:
        jdbc:
          enabled: true
          sql: SELECT key1, value1 from config_properties where APPLICATION=? and PROFILE=? and LABEL=?


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
